"""
Concept formation, verified on experiences generated by the real physics.

Things are made from the world's materials, perceived by handling through
the real perception module, and paired with outcomes the body would
register. The learner is never told what anything is. The test, playing
observer, knows which material each experience came from and uses that
only to score how well the learner's own categories line up with it.

    python -m tests.v2.test_concepts
"""

from __future__ import annotations

import ast
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

import zimulation.behavior.params  # noqa: F401  (declares on import)
import zimulation.biology.params  # noqa: F401
import zimulation.cognition.params  # noqa: F401
import zimulation.world.params  # noqa: F401
from zimulation.cognition import concepts as K
from zimulation.cognition import perception as PC
from zimulation.core.parameters import REGISTRY as R
from zimulation.core.rng import Streams
from zimulation.world import objects as O
from zimulation.world.materials_data import MATERIALS
from zimulation.world.space import Terrain

CELL = Terrain(4, Streams(1).get("t")).at(1, 1)


def _flake(s):
    core = O.Thing(None, MATERIALS["flint"], 0.6, 0.15)
    hammer = O.Thing(None, MATERIALS["granite"], 1.0, 0.2)
    frags = O.strike(hammer, core, R.get("fracture_energy_scale") * 0.6 * 3, s)
    return max(frags, key=lambda f: f.mass_kg)


def _tuber(s):
    t = O.Thing(None, MATERIALS["tuber"], 0.15 + 0.1 * s.random(), 0.1)
    t.moisture = 0.6
    return t


def _experiences(n, seed, outcomes_follow_kind=True):
    """(features, outcome, true_kind) from real things, perceived by touch."""
    s = Streams(seed).get("world")
    see = Streams(seed).get("see")
    out = []
    for i in range(n):
        kind = "hard" if i % 2 else "soft"
        thing = _flake(s) if kind == "hard" else _tuber(s)
        p = PC.sense_thing(thing, CELL, CELL, None, i, 1.0, 0.0, see,
                           touching=True)
        if outcomes_follow_kind:
            outcome = {"pain": thing.cutting_power,
                       "satiation": 1.0 if kind == "soft" else 0.0}
        else:
            outcome = {"pain": s.random(), "satiation": s.random()}
        out.append((p.features, outcome, kind))
    return out


def _learn(exps, owner=1):
    c = K.Concepts(owner)
    for i, (f, o, _) in enumerate(exps):
        c.learn(f, o, i, trace_id=i)
    c.prune()
    return c


def test_categories_form_from_physics_without_being_named():
    """
    From perceived heft, hardness, edge, wetness and warmth alone, the
    learner's categories line up with kinds of matter it was never told
    about. Purity is scored by the observer; the learner sees none of it.
    """
    exps = _experiences(160, 3)
    c = _learn(exps)
    assert 2 <= len(c.items) <= 6, f"{len(c.items)} categories"
    buckets = {}
    for f, _, kind in exps:
        cat = c.categorize(f)
        if cat is not None:
            buckets.setdefault(cat.id, []).append(kind)
    placed = sum(len(v) for v in buckets.values())
    majority = sum(max(v.count("hard"), v.count("soft"))
                   for v in buckets.values())
    assert placed > 0.8 * len(exps), "most experiences fit no category"
    purity = majority / placed
    assert purity > 0.9, f"categories are only {purity:.0%} pure"
    for cat in c.items:
        assert cat.id[0] == "concept" and isinstance(cat.id[2], int), \
            f"a category carries a name: {cat.id}"


def test_a_category_is_kept_only_if_it_predicts():
    """
    Same things, same perception. Where consequences follow kind, the
    categories survive; where consequences are random, grouping by look
    tells nothing and the categories are dissolved.
    """
    useful = _learn(_experiences(160, 4, outcomes_follow_kind=True))
    useless = _learn(_experiences(160, 4, outcomes_follow_kind=False))
    assert len(useful.items) >= 2, "predictive categories were dissolved"
    assert len(useless.items) < len(useful.items), (
        f"{len(useless.items)} categories survived in a world where "
        f"appearance predicts nothing")


def test_categories_let_an_agent_anticipate():
    """
    The point of having them: a new thing is expected to do what its kind
    did. Judged over a hundred fresh things of each kind rather than one,
    because a single atypical reading -- a tuber that happens to feel dry
    and edged -- is rightly hedged toward what follows experience in
    general. The first version of this test used one such reading (the
    model gave it a 42% chance of being something new) and mistook that
    honesty for failure.
    """
    c = _learn(_experiences(160, 5))
    soft, hard = [], []
    for f, _, kind in _experiences(200, 99):
        _, guess = c.predict(f)
        (soft if kind == "soft" else hard).append(guess["satiation"])
    assert sum(soft) / len(soft) > 0.8, "fresh soft things not expected to sate"
    assert sum(hard) / len(hard) < 0.2, "fresh hard things expected to sate"
    right = sum(g > 0.5 for g in soft) + sum(g < 0.5 for g in hard)
    assert right >= 190, f"only {right}/200 anticipated on the right side"


def test_a_known_kind_stays_recognisable_despite_noise():
    """
    The flaw that rebuilt this module: under the first version one
    ordinary noise draw on felt warmth left a fresh flake outside every
    category. Two hundred fresh things, from a stream the learner never
    saw, must nearly all be recognised as what their kind was.
    """
    exps = _experiences(160, 3)
    c = _learn(exps)
    members = {}
    for f, _, kind in exps:
        cat = c.categorize(f)
        if cat is not None:
            members.setdefault(cat.id, []).append(kind)
    label = {k: ("hard" if v.count("hard") >= v.count("soft") else "soft")
             for k, v in members.items()}
    right = unknown = 0
    for f, _, kind in _experiences(200, 77):
        cat = c.categorize(f)
        if cat is None:
            unknown += 1
        elif label.get(cat.id) == kind:
            right += 1
    assert unknown <= 10, f"{unknown}/200 familiar things unrecognised"
    assert right >= 190, f"only {right}/200 recognised as their kind"


def test_the_evidence_obeys_the_chain_rule():
    """
    Consolidation rests on the marginal likelihood of a category's members.
    It must equal the product of successive predictive densities --
    p(x1..xn) = p(x1) p(x2|x1) ... -- or the Occam factor that decides
    merges is wrong. Checked to rounding error.
    """
    prior = (0.3, 0.04, R.get("concept_prior_strength"))
    stats = (0, 0.0, 0.0)
    chain = 0.0
    for x in (0.21, 0.35, 0.18, 0.4, 0.29):
        mu, var, kn, dof = K._posterior(stats, prior)
        chain += K._student_logpdf(x, mu, math.sqrt(var * (1 + 1 / kn)),
                                   dof)
        stats = K._add(stats, x)
    assert abs(chain - K._log_evidence(stats, prior)) < 1e-9,         f"{chain} != {K._log_evidence(stats, prior)}"


def test_consolidation_merges_a_split_kind_and_keeps_two_apart():
    def split(gap, seed):
        s = Streams(seed).get("x")
        c = K.Concepts(1)
        a, b = c._found(0, 0), c._found(1, 1)
        for i in range(60):
            for host, centre in ((a, 1.0), (b, 1.0 + gap)):
                f = {"heft": s.gauss(centre, 0.05)}
                c._absorb(host, f, {"pain": 0.0}, i)
                c._see(f, {"pain": 0.0})
        c.consolidate()
        return c
    for seed in range(5):
        one = split(0.0, seed)
        assert len(one.items) == 1, "one kind split in two was left split"
        assert one.items[0].absorbed, "the merge kept no lineage"
        assert len(split(1.0, seed).items) == 2, "two kinds were merged"


def test_counterexamples_lower_confidence():
    s = Streams(6).get("x")
    steady, shaken = K.Concepts(1), K.Concepts(2)
    for i in range(40):
        f = {"heft": 1.0 + 0.01 * s.random()}
        steady.learn(f, {"pain": 0.0}, i, trace_id=i)
        shaken.learn(f, {"pain": 0.0 if i % 3 else 1.0}, i, trace_id=i)
    cs, ck = steady.items[0], shaken.items[0]
    assert ck.n_counter > 0 and ck.counterexamples
    assert shaken.confidence(ck) < steady.confidence(cs)


def test_every_category_records_where_it_came_from():
    c = K.Concepts(owner=42)
    cat = c.learn({"heft": 1.0}, {"pain": 0.0}, time=17, trace_id=301)
    assert cat.creator == 42 and cat.origin_time == 17
    assert cat.origin_trace == 301 and 301 in cat.examples
    assert cat.received_from is None, "a self-made category claims a donor"


def test_the_module_contains_no_ontology():
    """
    Section 19: no human categories in the machinery. Identifiers and
    string constants (docstrings excluded, since they explain) must not
    name a material or a kind of thing.
    """
    src = (ROOT / "zimulation" / "cognition" / "concepts.py").read_text(
        encoding="utf-8")
    tree = ast.parse(src)
    docs = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.ClassDef)):
            body = node.body
            if (body and isinstance(body[0], ast.Expr)
                    and isinstance(body[0].value, ast.Constant)):
                docs.add(id(body[0].value))
    words = set(MATERIALS) | {"food", "tool", "weapon", "stone", "wood",
                              "meat", "fruit", "edible", "animal", "plant",
                              "danger", "fire"}
    hits = []
    for node in ast.walk(tree):
        text = None
        if isinstance(node, ast.Name):
            text = node.id
        elif isinstance(node, ast.Attribute):
            text = node.attr
        elif (isinstance(node, ast.Constant) and isinstance(node.value, str)
              and id(node) not in docs):
            text = node.value
        if text and any(w in text.lower() for w in words):
            hits.append(text)
    assert not hits, f"concepts.py names kinds of thing: {sorted(set(hits))}"


def test_concept_formation_is_deterministic():
    def run():
        c = _learn(_experiences(80, 7))
        return [(x.id, x.n, round(x.outcome_mean.get("satiation", -1), 12))
                for x in c.items]
    assert run() == run()


def _run_all():
    ok = fail = 0
    for name, fn in sorted(globals().items()):
        if not name.startswith("test_") or not callable(fn):
            continue
        try:
            fn()
            print(f"  PASS  {name}")
            ok += 1
        except AssertionError as e:
            print(f"  FAIL  {name}: {e}")
            fail += 1
        except Exception as e:
            print(f"  ERROR {name}: {type(e).__name__}: {e}")
            fail += 1
    print(f"\n{ok} passed, {fail} failed")
    return fail


if __name__ == "__main__":
    sys.exit(1 if _run_all() else 0)
