"""
Parameter audit and docs/PARAMETERS.md.

Runs every V2 test suite in one process, so that the registry records which
parameters are actually read, then:

  - lists parameters declared and never read, separating those no code
    refers to at all (dead) from those the code refers to but no test
    exercised (a coverage gap, not dead code);
  - writes docs/PARAMETERS.md from the registry: every declared number,
    grouped by category, with its default, units, range, source,
    uncertainty and the modules that use it (contract sections 55 and 66).

    python tools/parameters_doc.py

The document is generated; edit the declarations, not the document.
"""

from __future__ import annotations

import contextlib
import importlib
import io
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

ORDER = ("H", "P", "B", "S", "N")


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def _load_params():
    for p in sorted((ROOT / "zimulation").rglob("params.py")):
        importlib.import_module(".".join(p.relative_to(ROOT).with_suffix("")
                                         .parts))


def _run_suites():
    results = {}
    for path in sorted((ROOT / "tests" / "v2").glob("test_*.py")):
        mod = importlib.import_module(f"tests.v2.{path.stem}")
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            failed = mod._run_all()
        last = buf.getvalue().strip().splitlines()[-1]
        results[path.stem] = (failed, last)
        print(f"  {path.stem}: {last}", file=sys.stderr)
    return results


def _sources():
    out = {}
    for p in (ROOT / "zimulation").rglob("*.py"):
        if p.name == "params.py" or p.name.endswith("_data.py"):
            continue
        out[p] = p.read_text(encoding="utf-8")
    return out


def _referenced(name, sources):
    quoted = re.compile(r"[\"']" + re.escape(name) + r"[\"']")
    if any(quoted.search(text) for text in sources.values()):
        return True
    # families read through f-strings, such as R.get(f"{name}_cap")
    for text in sources.values():
        for stem, suffix in re.findall(r'f"\{(\w+)\}(_\w+)"', text):
            if name.endswith(suffix):
                head = name[: -len(suffix)]
                if re.search(r"[\"']" + re.escape(head) + r"[\"']", text):
                    return True
    return False


def main():
    _load_params()
    from zimulation.core.parameters import CATEGORIES, CLAIM_BEARING
    from zimulation.core.parameters import REGISTRY as R

    results = _run_suites()
    failed = sum(f for f, _ in results.values())
    params = R.all()
    unused = R.unused()
    sources = _sources()
    dead = [n for n in unused if not _referenced(n, sources)]
    untested = [n for n in unused if n not in dead]

    cats = R.by_category()
    counts = {k: len(cats.get(k, ())) for k in CATEGORIES}
    claims = sum(counts[k] for k in CLAIM_BEARING)

    L = ["# Parameters", ""]
    L.append("Generated by `tools/parameters_doc.py`, which runs every V2 "
             "test suite in one process and reads the registry; edit the "
             "declarations, not this file. Every number the causal code "
             "uses is declared with its category, units, default, allowed "
             "range, source and uncertainty (contract section 55); an "
             "undeclared number fails the build.")
    L.append("")
    L.append(f"Registry hash `{R.hash()}` - **{len(params)}** declared: "
             + ", ".join(f"{k} {counts[k]}" for k in ORDER)
             + f". **{claims}** assert something about the real world "
             "(P, B, H); the rest are architecture (S) and arithmetic (N).")
    L.append("")
    L.append(f"Suites run for this audit: {len(results)}, failures: "
             f"{failed}.")
    for k in ORDER:
        names = cats.get(k, [])
        if not names:
            continue
        L += ["", f"## {k} - {CATEGORIES[k]} ({len(names)})", ""]
        L.append("| name | default | units | range | source | uncertainty |"
                 " modules |")
        L.append("|---|---|---|---|---|---|---|")
        for n in names:
            p = params[n]
            low, high = getattr(p, "low", None), getattr(p, "high", None)
            rng = ("" if low is None and high is None
                   else f"{low} .. {high}")
            L.append("| `%s` | %s | %s | %s | %s | %s | %s |" % (
                n, _cell(getattr(p, "default", "")),
                _cell(getattr(p, "units", "")), _cell(rng),
                _cell(getattr(p, "source", "")),
                _cell(getattr(p, "uncertainty", "")),
                _cell(", ".join(getattr(p, "modules", []) or []))))
    L += ["", f"## Declared but never read by any test ({len(unused)})", ""]
    if not unused:
        L.append("None.")
    else:
        if dead:
            L.append("No code refers to these at all -- dead declarations: "
                     + ", ".join(f"`{n}`" for n in dead) + ".")
            L.append("")
        if untested:
            L.append("Code refers to these but no test exercised them -- a "
                     "coverage gap, not dead code: "
                     + ", ".join(f"`{n}`" for n in untested) + ".")
    L.append("")
    (ROOT / "docs" / "PARAMETERS.md").write_text("\n".join(L),
                                                 encoding="utf-8")
    print(f"declared {len(params)} ({', '.join(f'{k} {counts[k]}' for k in ORDER)}); "
          f"suites {len(results)}, failures {failed}; never read by a test "
          f"{len(unused)}: dead {dead}; untested {untested}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
